### ISSUE TITLE
AuroraCrashPatcher v1.2 issues

### ISSUE THREAD

**Issue by Steve842936** [StelioKontosXBL/AuroraCrashPatcher#4]
Hello!
  When using the AuroraCrashPatcher.xex v1.2 plugin, I encountered the following problem:
  In games, after launching the [REFRESH] icon, I always download only 3 files for me.  You did not automatically add these files to the components of the game.  I had to restart Aurora.  Now I'm there to add the 3 files in principle, but nothing changes.  Game covers not show and not downloading, even though they used to work without a patch.
Time refresh not working after restart.

 What causes the biggest problem is that after removing the plugin from DashLaunch, those things still persist.

 I think too much hardware, software versions and DL settings are causing the problem.  Maybe we should focus more on "NetDbgDll.xex".

 The good news, however, is that CRASH events (unhandled exception) have disappeared.

 I downloaded AuroraCrashPatcher v1.2 for the following reason:

 In Aurora, after change the marketplace region, an unhandled exception occurred for games when [REFRESH] was selected.  It writes "NetDbgDll.xex" incorrectly load in the error log.  Only downloading and applying covers could work normally.  I still don't know if moving the "backup" games to the new HDD along with the rehashed resigned savegame backups and DLCs may have something to do with it.

 I used to use FSD, but after the HDD upgrade, the empty covers after the manual search at older games (not xbla) didn't appear, so I couldn't launch them, which is a mystery to me.

 System: Aurora 0.7b1 (hotfix release)
 Kernel: 2.0.17502.0
 Hardware: Xbox 360 s Slim Trinity
 Hardware production time: 2010-06-14
 DashLaunch version: V3.10 (535)

Best Regards: Steve

[GOOGLE TRANSLATED TEXT]

**Comment by Ste1io** [comment]
Your problem is due to having liveblock/livestrong enabled. Disable liveblock/livestrong, reboot, and refresh the titles again. The first time scanning/refreshing your titles on the HDD require Aurora to download the manifest data from Microsoft, before then downloading the actual covers/backgrounds/etc from either Unity or Microsoft. After one complete scan with liveblock/livestrong disabled, the manifest data will be cached and futures scans or title refreshes will work properly.

_This is due to how Aurora works - and has nothing to do with the patch._

The problem which you said persists even after removing the patch would, indeed, persist for as long as those two settings are enabled. Because the patch is a plugin, and does nothing more than "filter out" the problematic api calls at runtime, there are no persistent changes on the system that could even remotely be related.

Regarding the rest of your post, if you look at the source code you'll see that nothing hardware related is being done. The patch itself is only a couple lines long, and I'm hooking a winsock function - not a function in Aurora. I went with the least intrusive approach possible that was both consistently reliable, and future-proof. Aside from the stupidly simple strcmp done in the hook, the rest is simply logic to ensure consistent interoperability for all users on all past/current versions of both titles given all the possible edge cases (of which there are plenty - such as using an outdated kernel build as you are - the current dash being 17559).

**Your solution:**

1. Put AuroraCrashPatcher back in plugins
2. Disable liveblock & livestrong
3. Reboot, Rescan, Rejoice.

...And update your dash.

**Comment by Ste1io** [comment]
@Steve842936 Did what I say to do fix your issue?

**Comment by Steve842936** [comment]
Hello!

   I managed to get it right.  It seems to be my fault.
  All downloads now work.

  The problem was:

  The network settings on the console were as follows:

   Usually I usually connect the console and the pc directly with a crosslink cable.  To do this, it is essential to use a manual ip address.  To use the mobile hotspot, I reset the wired connection on the console to automatic, but left the dns manually.  This error lead to the console appearing to have downloaded something but still not downloaded anything.

   I will delete the dns settings in the near future.

   Now after setting the ip and dns connection to automatic, all downloads will work.

   However, I will enable the liveblock option.  Disabling it seems risky to me.  I just keep livestrong off.  Downloads still work that way.  I'm not going to go live anyway.

   Thank you for your efforts, this patch is great!  It works great!

   My first comment would be if it was deleted or closed.

  Best Regards: Steve

  System: Aurora 0.7b1 (hotfix release)
  Kernel: 2.0.17502.0
  Hardware: Xbox 360's Slim Trinity
  Hardware production time: 2010-06-14
  DashLaunch version: V3.10 (535)

  [GOOGLE TRANSLATED TEXT]
